---
name: Documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allow running this workflow manually (Actions tab)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Configure GitHub Pages"
        uses: actions/configure-pages@v5

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Install UV"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "Setup Python"
        run: |
          cd docs/
          uv python install
        with:
          python-version-file: "pyproject.toml"

      - name: "Install project dependencies"
        run: |
          cd docs/
          uv sync --locked --all-extras --dev

      - name: "Build pages artifact"
        run: |
          cd docs/
          uv run zensical build --clean

      - name: "Upload pages artifact"
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/public
          
      - name: "Deploy pages artifact"
        id: deployment
        uses: actions/deploy-pages@v4
